### ISSUE TITLE
hook exec timeout is too short

### ISSUE THREAD

**Issue by robertek** [dsh2dsh/zrepl#10]
While using the pre/post job hooks I have noticed it has a fixed timeout of 30s. This may be too short. For example, on one of my FreeBSD boxes I have an external usb hdd box which is woken up before the job. Unfortunately the spinning rust needs around 15-20s to properly settle and than the pool can be imported. So this hook scrip takes always around 32-35s and is killed by timeout. Fortunately does not have any effect for the functionality, since the pool import is nearly finished (the job is run ok). But even if the job pass it is marked as failed, because of the timeout hit.

It would be nice if it can be configured. If not, maybe raising this to at least 60s would be fine. It will be probably enough even from remote pool waking.

Sorry if this report is duplicated, I'm not really sure now if we have discussed that before already.

**Comment by dsh2dsh** [comment]
Hi,

> While using the pre/post job hooks I have noticed it has a fixed timeout of 30s.

Not a problem at all. This timeout isn't fixed, it has default value 30 seconds. You can change it with `timeout` key, like

    ```yaml
    - name: "zroot-to-zdisk"
      type: "push"
      hooks:
        pre:
          path: "/root/bin/zrepl_hook.sh"
          args: [ "pre" ]         # optional positional parameters
          env:                    # optional environment variables
            ZREPL_FOOBAR: "foo"
          timeout: "30s"          # optional, default is 1m
          # don't continue job if exit status is nonzero (default: false)
          err_is_fatal: true
        post:
          path: "/root/bin/zrepl_hook.sh"
          args: [ "post" ]        # optional positional parameters
          env:                    # optional environment variables
            ZREPL_FOOBAR: "bar"
          timeout: "0s"           # without timeout at all
    ```

Please test it works as expected. Anyway, I'll increase default timeout from 30 seconds to 1 minute in the next release and add it into README.md.

Thanks.
