### ISSUE TITLE
Omitting "pruning:" in push type job causes error

### ISSUE THREAD

**Issue by fluoros-jp** [dsh2dsh/zrepl#12]
Hello,

While the documentation says it's possible to omit `pruning:` at all, when I tried to run `zrepl configcheck` on a push type job config file without `pruning:`, following error message was shown;
`could not parse config: validate config: Key: 'Config.jobs[0].Ret.ActiveJob.pruning' Error:Field validation for 'pruning' failed on the 'required' tag`

The config file is as follows;
```
jobs:
  - name: "repl"
    type: "push"
    connect:
      type: "http"
      server: "http://192.168.0.224:8888"
      listener_name: "sink"
      client_identity: "server-backup"
    datasets:
      - pattern: "tank/data"
    snapshotting:
      type: "periodic"
      cron: "0 4 * * *"
      prefix: "snap-"
      timestamp_format: "20060102-150405"
      timestamp_local: false
```

The version I used is v0.9.9.

Thanks.

**Comment by dsh2dsh** [comment]
Hi,

> it's possible to omit `pruning:` at all

Well, actually I meant, now it's possible to omit `pruning:` at all in case like

``` yaml
pruning:
  keep:
    - type: "regex"
      regex: ".*"
```

or one of `keep_sender:` or `keep_receiver:` in case like:

  ``` yaml
pruning:
  keep_sender:
    - type: "regex"
      regex: ".*"
  keep_receiver:
```

Could you describe your use case? Don't you use pruning at all?
