### ISSUE TITLE
crash on manual push job execution when the sink dataset is not created yet

### ISSUE THREAD

**Issue by robertek** [dsh2dsh/zrepl#4]
I'm testing a simple manual push job to sync to external drive and I'm hitting a crash.

The crash stack is following:
```
❯ zrepl --config zrepl.yml daemon
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xaefc8f]

goroutine 194 [running]:
github.com/dsh2dsh/zrepl/replication/logic.(*Filesystem).doPlanning(0x86c14e070, {0xfbb000, 0x86c11ea20}, 0x1)
        github.com/dsh2dsh/zrepl/replication/logic/replication_logic.go:530 +0xcef
github.com/dsh2dsh/zrepl/replication/logic.(*Filesystem).PlanFS(0x86c1223d0?, {0xfbb000?, 0x86c11ea20?}, 0x0?)
        github.com/dsh2dsh/zrepl/replication/logic/replication_logic.go:141 +0x25
github.com/dsh2dsh/zrepl/replication/driver.(*fs).do.func1()
        github.com/dsh2dsh/zrepl/replication/driver/replication_driver.go:536 +0x129
github.com/dsh2dsh/zrepl/util/chainlock.(*L).DropWhile(0x2bea895d7ae8?, 0x86c017ba0?)
        github.com/dsh2dsh/zrepl/util/chainlock/chainlock.go:40 +0x70
github.com/dsh2dsh/zrepl/replication/driver.(*fs).do(0x86c0b4320, {0xfbb000, 0x86c11ea20}, 0x86c1223d0, 0x0, 0x1, {0xfbb038, 0x86c09fb30})
        github.com/dsh2dsh/zrepl/replication/driver/replication_driver.go:525 +0x255
github.com/dsh2dsh/zrepl/replication/driver.(*attempt).doFilesystems.func1(0x86c0b4320)
        github.com/dsh2dsh/zrepl/replication/driver/replication_driver.go:480 +0x138
created by github.com/dsh2dsh/zrepl/replication/driver.(*attempt).doFilesystems in goroutine 117
        github.com/dsh2dsh/zrepl/replication/driver/replication_driver.go:474 +0x219
```

I have cleaned the zrepl.yml confing as much as possible.
```
jobs:
  - name: "hourly-snap"
    type: "snap"
    filesystems: &filesystems
      "mpool/test": true
    snapshotting:
      type: "periodic"
      cron: "10 * * * *"
      prefix: "zrepl_hourly_"
    pruning: &keep-all

  - name: "bpool"
    type: "sink"
    root_fs: "bpool/zrepl"
    serve:
      type: "local"
      listener_name: "bpool"

  - name: "mpool-to-bpool"
    type: "push"
    connect:
      type: "local"
      listener_name: "bpool"
      client_identity: "localhost"
    filesystems: *filesystems
    snapshotting:
      type: "manual"
    pruning:
      keep_sender:
        - type: "regex"
          negate: true
          regex: "^zrepl_"
        - type: "last_n"
          count: 2
          regex: "^zrepl_hourly_"
      keep_receiver:
        - type: "last_n"
          count: 90
          regex: "^zrepl_hourly_"
```

the mpool/test is a simple empty dataset with one zrepl_hourly_xxx snapshot. The bpool/zrepl is newly created dataset without any descendants.

It crashes when I call
`zrepl signal wakeup mpool-to-bpool`

This is in the log:
```
2024/10/18 18:14:34 INFO got signal subsystem=internal job=_control op=wakeup
2024/10/18 18:14:34 INFO with RPC timeout subsystem=rpc.ctrl job=mpool-to-bpool timeout=1m0s
2024/10/18 18:14:34 INFO start replication subsystem=job job=mpool-to-bpool
2024/10/18 18:14:34 INFO start planning subsystem=repl job=mpool-to-bpool
2024/10/18 18:14:34 INFO "/sbin/zfs list -H -p -o name -r -t filesystem,volume" subsystem=zfs.cmd job=mpool-to-bpool
2024/10/18 18:14:34 INFO "/sbin/zfs get -Hp -o name,property,value,source zrepl:placeholder bpool/zrepl" subsystem=zfs.cmd job=bpool
2024/10/18 18:14:34 INFO "/sbin/zfs list -H -p -o name -r -t filesystem,volume" subsystem=zfs.cmd job=bpool
2024/10/18 18:14:34 INFO "/sbin/zfs get -Hp -o name,property,value,source zrepl:placeholder mpool/test" subsystem=zfs.cmd job=mpool-to-bpool
2024/10/18 18:14:34 INFO "/sbin/zfs list -H -p -o name,guid,createtxg,creation,userrefs -r -d 1 -t bookmark,snapshot -s createtxg mpool/test" subsystem=zfs.cmd job=mpool-to-bpool
2024/10/18 18:14:34 INFO conflict automatically resolved subsystem=repl job=mpool-to-bpool conflict="no common snapshot or suitable bookmark between sender and receiver:\n  sorted sender versions:\n    @zrepl_hourly_xxx\n  sorted receiver versions:\n" filesystem=mpool/test
```

This is on a current freebsd 14.1 zrepl-dsh2dsh version 0.8.5

I have also tested a slightly modified config that works also on original zrepl and with the original zrepl it works ok. If I run this on the zrepl-dsh2dsh it fails the same.

```
jobs:
  - name: "hourly-snap"
    type: "snap"
    filesystems: &filesystems
      "mpool/test": true
    snapshotting:
      type: "cron"
      cron: "10 * * * *"
      prefix: "zrepl_hourly_"
    pruning: 
      keep:
        - type: "regex"
          regex: ".*"

  - name: "bpool"
    type: "sink"
    root_fs: "bpool/zrepl"
    serve:
      type: "local"
      listener_name: "bpool"
    recv:
      placeholder:
        encryption: inherit

  - name: "mpool-to-bpool"
    type: "push"
    connect:
      type: "local"
      listener_name: "bpool"
      client_identity: "localhost"
    filesystems: *filesystems
    snapshotting:
      type: "manual"
    pruning:
      keep_sender:
        - type: "regex"
          negate: true
          regex: "^zrepl_"
        - type: "last_n"
          count: 2
          regex: "^zrepl_hourly_"
      keep_receiver:
        - type: "last_n"
          count: 90
          regex: "^zrepl_hourly_"

```

I have not tested the master branch version of zrepl yet.
