### ISSUE TITLE
Feature: pre/post job hook

### ISSUE THREAD

**Issue by robertek** [dsh2dsh/zrepl#5]
What I'm missing in zrepl is a command hook before some job starts and when finished.

To explain a scenario I use regularly.

1. resume usb external drive
2. import pool
3. backup
4. export pool
5. suspend usb drive

I do this by external cronjob that do the steps and then signal zrepl to do the job. I need to wait for a fixed time (getting proper finish status from zrepl is hard) and then do the final steps to suspend the drives.

I can imagine something like:

```
  - name: "mpool-to-bpool"
    type: "push"
    connect:
      type: "local"
      listener_name: "bpool"
      client_identity: "localhost"
    filesystems: *filesystems
    hooks:
       pre: /some/path/resume_pool.sh
       post: /some/path/suspend_pool.sh
......
```

I'm not a go programmer, but I may try to look at it.
